# netlify.toml

# Standard build settings
[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# ðŸ’¡ Image Optimization (Notion images ko allow karne ke liye)
[images]
  remote_images = [
    "s3.us-west-2.amazonaws.com",
    "prod-files-secure.s3.us-west-2.amazonaws.com"
  ]

# React Router (SPA) redirect
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
